#!/bin/sh

 ##############################################################################
 #                                                                            #
 # SUSE Paste script                                                          #
 #                                                                            #
 # Copyright (C) 2007-2010 by Michal Hrusecky <Michal@Hrusecky.net>           #
 #               2022 modified by Victorhck                                   #
 #                                                                            #
 # This program is free software: you can redistribute it and/or modify       #
 # it under the terms of the GNU General Public License as published by       #
 # the Free Software Foundation, either version 3 of the License, or          #
 # (at your option) any later version.                                        #
 #                                                                            #
 # This program is distributed in the hope that it will be useful,            #
 # but WITHOUT ANY WARRANTY; without even the implied warranty of             #
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
 # GNU General Public License for more details.                               #
 #                                                                            #
 # You should have received a copy of the GNU General Public License          #
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
 #                                                                            #
 ##############################################################################

# By default paste code from stdin

INPUT="<-"
TYPE="code"
API_KEY=""
file_selected=0

# Read configuration file

[ -r ~/.susepaste ] && . ~/.susepaste

# Process the command line parameters

while [ "$1" ]; do
	case "x$1" in
	"x-t" )
		TITLE="$2"
		shift 2 ;;
	"x-n" )
		NICK="$2"
		shift 2 ;;
	"x-e" )
		EXPIRE="$2"
        case "$EXPIRE" in
            "30m")
                EXPIRE=30
                ;;
            "1h")
                EXPIRE=60
                ;;
            "6h")
                EXPIRE=360
                ;;
            "12h")
                EXPIRE=720
                ;;
            "1d")
                EXPIRE=1440
                ;;
            "1w")
                EXPIRE=10080
                ;;
            "1m")
                EXPIRE=40320
                ;;
            "3m")
                EXPIRE=151200
                ;;
            "1y")
                EXPIRE=604800
                ;;
            "2y")
                EXPIRE=1209600
                ;;
            "3y")
                EXPIRE=1814400
                ;;
            "0")
                EXPIRE=0
                ;;
        esac
		shift 2 ;;
	"x-k" )
		KEY="$2"
		shift 2 ;;
    "x-f")
        FILE="$2"
        file_selected=1
        shift 2
        ;;
	* )
		echo "openSUSE Paste script"
		echo ""
		echo " usage:"
		echo "   susepaste [-n nick] [-t title] [-e expire] [-f <file> or <path/to/file>]"
		echo "(expire: 30m=30minutes; 1h=1hour; 6h=6hours; 12h=12hours; 1d=1day; 1w=1week; 1m=1month; 3m=3months; 1y=1year; 2y=2years; 3y=3years; 0=never)"
		echo ""
		exit 0 ;;
	esac
done

# Key handling

if [ "$KEY" ]; then
	if [ "`expr substr "$KEY" 1 4`" = "KEY:" ]; then
		KEY="`echo "$KEY" | sed 's|^KEY:||'`"
	fi
	API_KEY=" -F api_key=$KEY "
fi

# Do we want to use stdin or paste content of the file?

if [ $file_selected -eq 1 ]; then
	if [ \! -r "$FILE" ]; then
		echo "Sorry, can't read the file: $FILE"
		exit 2
	fi
	INPUT="<$FILE"
	[ "$TITLE" ] || TITLE="`basename $FILE`"
	TMP=""
	for i in /usr/share/susepaste/lang-mappings.sed \
		~/.susepaste_lang_mappings.sed; do
		[ -r "$i" ] && TMP="`LANG=C file -iLb "$FILE" | sed -nf "$i"`"
        echo "sintaxis == $TMP"
	done
	if [ "$TMP" ] && [ -z "$SYNTAX" ]; then
		SYNTAX="$TMP"
	fi
fi

# Defaults if nothing was specified

# Nickname displayed as an author
[ "$NICK"     ] || NICK="`whoami`"
# Title of your paste
[ "$TITLE"    ] || TITLE="`whoami`'s paste"
# Syntax highlighting (for possible values check the documentation)
[ "$SYNTAX"   ] || SYNTAX="text"
# Time to live for your paste in minutes (for possible values check the documentation)
[ "$EXPIRE"   ] || EXPIRE=60

# Real pasting and getting back the URL of the paste

URL="`
curl -v -F "$TYPE=$INPUT" -F "title=$TITLE"  -F "expire=$EXPIRE"   \
        -F "name=$NICK"   -F "submit=submit" -F "lang=$SYNTAX"     \
	$API_KEY                                                   \
        https://susepaste.org 2>&1 | sed -n 's|<\ [lL]ocation:\ ||p' `"

# Check the results and inform the user

if expr "$URL" : "^https://susepaste.org/[0-9a-f]\+" > /dev/null; then
	ID="`echo "$URL"`" # | sed 's|^'https://susepaste.org/\([0-9a-f]\+\)[^0-9a-f]*|\1|'`"
	echo "Pasted as:"
	echo "   $ID"
	echo "   $ID"
	if [ -x /usr/bin/xclip ]; then
		echo "$ID" | xclip -selection clipboard
		echo "Link is also in your clipboard."
	fi
else
	echo "Paste failed :-("
fi
